module Tenant
  module PackageManager
    def create_package_json(db_type)
      # Base dependencies for Express application
      dependencies = {
        "express" => "^4.18.2",
        "body-parser" => "^1.20.2",
        "dotenv" => "^16.3.1",
        "cors" => "^2.8.5"
      }
      
      # Add database-specific dependencies
      case db_type.to_s.downcase
      when 'sequelize', 'sql', 'mysql', 'postgres', 'postgresql'
        dependencies["sequelize"] = "^6.35.1"
        dependencies["pg"] = "^8.11.3" # For PostgreSQL
        dependencies["pg-hstore"] = "^2.3.4" # For PostgreSQL
        # Add MySQL if needed
        dependencies["mysql2"] = "^3.6.5" if db_type.to_s.downcase == 'mysql'
      when 'prisma'
        dependencies["@prisma/client"] = "^5.6.0"
      else # Default to MongoDB
        dependencies["mongoose"] = "^8.0.1"
      end
      
      # Create package.json content
      package_json = {
        "name" => "express-app",
        "version" => "1.0.0",
        "description" => "Express application generated by Dwelling",
        "main" => "app.js",
        "scripts" => {
          "start" => "node app.js",
          "dev" => "nodemon app.js"
        },
        "dependencies" => dependencies,
        "devDependencies" => {
          "nodemon" => "^3.0.1"
        }
      }
      
      # Add database-specific dev dependencies
      if db_type.to_s.downcase == 'prisma'
        package_json["devDependencies"]["prisma"] = "^5.6.0"
      elsif ['sequelize', 'sql', 'mysql', 'postgres', 'postgresql'].include?(db_type.to_s.downcase)
        package_json["devDependencies"]["sequelize-cli"] = "^6.6.2"
      end
      
      # Write package.json file
      File.write("#{@express_path}/package.json", JSON.pretty_generate(package_json))
    end
    
    def install_dependencies
      Dir.chdir(@express_path) do
        puts "Installing dependencies..."
        system("npm install")
      end
    end
    
    def initialize_prisma
      Dir.chdir(@express_path) do
        puts "Initializing Prisma..."
        system("npx prisma init")
      end
    end
    
    def initialize_sequelize
      Dir.chdir(@express_path) do
        puts "Initializing Sequelize..."
        system("npx sequelize-cli init")
      end
    end
  end
end 